import { test, expect } from '@playwright/test';
import path from 'path';

test('invalid login', async ({ page }) => {
  const filePath = 'file://' + path.resolve('index.html');

  await page.goto(filePath);

  await page.fill('#username', 'admin');
  await page.fill('#password', 'wrongpass');

  await page.click('button');

  await expect(page.locator('#message')).toHaveText('Invalid username or password');
});
